### PR TITLE
added fixed version of excel criteria catalog

### PR DESCRIPTION
**Pull request by expeditionengineer**

### CODE REVIEW

**Comment by expeditionengineer** [comment]
- should fix issue #62 
- fixed error in criteria catalog excel file with doubled IDS

**Comment by c0nb4** [comment]
The Selenium tests are failing again @expeditionengineer

**Review by c0nb4 — COMMENTED** [review]
See previous comment.

**Comment by expeditionengineer** [comment]
- test has passed

**Review by c0nb4 — APPROVED** [review]

**Pull request merged**
