### PR TITLE
Filip figma backlog

### PR DESCRIPTION
**Pull request by expeditionengineer**
- implemented new explanation expandable component on all listing sites like shown here: https://www.figma.com/design/9isFFZdptnsTNPVPhOcC5d/Wissensplattform-Entwurf?node-id=4196-32705&node-type=frame&t=SmeUaMZOb73AvOD6-0
- added glow effect on card items across all sites
grafik

### CODE REVIEW

**Comment by c0nb4** [comment]
Nice!

**Comment by c0nb4** [comment]
@expeditionengineer  can you confirm whether this error is in my local build? 
grafik

**Comment by c0nb4** [comment]
@nlongn22 

grafik
 
 
 Can you fix this, so it spells CityGML? Please also check the po files.

**Comment by c0nb4** [comment]
grafik

**Review by c0nb4 — CHANGES_REQUESTED** [review]
Please see the comments in the pull request.

**Comment by nlongn22** [comment]
I will look into it.

**Comment by expeditionengineer** [comment]
I think you need to transpile the SCSS using the folowing command: "npx webpack"

**Comment by c0nb4** [comment]
> I think the problems arise since you use old css-stylesheets. Could you transpile the up-to-date scss to css and review again the layout? The command should be "npx webpack" when in the root of the repo

Thanks, that was the error

**Comment by c0nb4** [comment]
grafik


Is the long sub link intended?

**Comment by expeditionengineer** [comment]
We can discuss, if we would like to shorten the text in the navbar item. From my side we can shorten it. I wanted to stick to the design, where the green line ends at the next dropdown-menu.

**Comment by c0nb4** [comment]
When translation is fixed, this can be merged. Moved the CityGML spelling error to the typo issue: https://github.com/TUB-DVG/wissen-digital-ewb/issues/106

**Comment by nlongn22** [comment]
CityGML spelling fixed but I'm not sure if we can fix the use cases graph language. It is an iframe that is built on its own with Dash.

**Review by c0nb4 — APPROVED** [review]

**Comment by c0nb4** [comment]
> CityGML spelling fixed but I'm not sure if we can fix the use cases graph language. It is an iframe that is built on its own with Dash.

I'll raise another Issue for this. You can take a look at the translation of e.g. the heat load.

**Pull request merged**
