### PR TITLE
Implementation of new data model and set of templates for the technical fcous

### PR DESCRIPTION
**Pull request by expeditionengineer**
This pull request implements the new data model for `Tools`, `Dataset`, `Protocol` and `Norm`, which @Cudok and me discussed. Here is a UML- daigram showing the new structure (Please note, that ckass notes to the classes Focus, Classification, ApplicationArea, TargetGroup, ... etc. were left out for clarity reasons)
technical_focus_data_structure
The 4 model classes inherit attributes from the abstract class `AbstractTechnicalFocus`
Since a lot of attributes are now shared across the 4 models a shared frontend template for the details-page makes in my eyes even more sense then before. 
I used the `details_page.html` template, which is also used in the other focuses to construct a details page, which is composed of 2 columns. In the smaller left column, short keyword like attributes can be shown, while on the bigger right column text attributes can be rendered. On the left side I used an template, which only uses attributes  from `AbstractTechnicalFocus`, which allows to reuse that template across the different details pages from the models.
Here is a picture of the tools details page:
image
Since moste of the attributes are already included in the database it looks well maintained.
norms dont look that good though:
image
Protocols:
image
Datasets:
image
Weatherdata:
image

Furthermore i created a universal template for the listing site. The new design of the content of a listing element should be more consistent.
Here are screenshots of the listing sites:
Weaterhdata
image
Datasets:
image
Protocols:
image
norms:
image
Tools:
image

Do you think we can use these templates? Where do you see room for improvement?

### CODE REVIEW

**Comment by c0nb4** [comment]
Thank you very much for the PR @expeditionengineer . I have several remarks before taking a look at the code. 

1. Why do the Norms, Protocol and Dataset have the follwoing attributes:

- targetGroup 
- developmentState 
- license
- programmingLanguages 

2. Maybe specifiicApplication should be reanemd to appliedBy? 

3. Why are there different states for no data, e.g. n/a or 0?

**Comment by expeditionengineer** [comment]
@Cudok can you say something about point 1.?
2.: Sure we can do that
3.: n/a is no state of the database but is rendered, when the attribute contains a None value or a blank string.
There are tuples of data, which contain strange values. If you check the excel file for the datasets for example, it contains alot of "0"s and "-" characters:
image
Here is the excel file: 
[datasets_with_weatherdata.xlsx](https://github.com/user-attachments/files/17949993/datasets_with_weatherdata.xlsx)

**Review by Cudok — APPROVED** [review]
seems ok, but I only scanned this PR.

**Comment by c0nb4** [comment]
targetGroup -> How to categorize user groups for dataset? (optional)
programmingLanguage -> only tools. 
license -> tools, dataset, norms, protcols, 
developmentState -> How to categorize data, protocolls or norms (maye pre norm). (opt.)

**Review by c0nb4 — APPROVED** [review]
LGTM

**Pull request merged**
